"use client";
import { useRouter } from "next/navigation";
import { useState, useTransition } from "react";
import { createLeadAction, deleteLeadAction, upsertLeadNoteAction } from "@/app/admin/leads/actions";
import { Modal } from "@/components/common/Modal";
import { StatusBadge } from "@/components/common/StatusBadge";
import { CONTACT_METHODS, LEAD_STATUSES, LEAD_STATUS_LABEL } from "@/lib/utils/constants";
import { formatKSTDateTime } from "@/lib/utils/date";
import type { LeadRow } from "@/lib/data/leads";
import type { Profile } from "@/types";

export function LeadTable({ rows, profiles, staffNames, role }: { rows: LeadRow[]; profiles: Profile[]; staffNames: string[]; role: string }) {
  const router = useRouter(); const [open,setOpen]=useState(false); const [memoId,setMemoId]=useState<string|null>(null); const [msg,setMsg]=useState<string|null>(null); const [pending,startTransition]=useTransition();
  function submit(fd: FormData){ startTransition(async()=>{ const r=await createLeadAction(fd); if(r.ok){setOpen(false); setMsg("저장되었습니다.");} else setMsg(r.error); }); }
  function saveMemo(fd: FormData){ startTransition(async()=>{ const r=await upsertLeadNoteAction(fd); setMsg(r.ok?"메모가 저장되었습니다.":r.error); }); }
  function del(id:string){ if(!confirm("삭제할까요?"))return; const fd=new FormData(); fd.set("id",id); startTransition(async()=>{const r=await deleteLeadAction(fd); setMsg(r.ok?"삭제되었습니다.":r.error);}); }
  return <>
    <div className="mb-4 flex justify-end"><button className="btn btn-primary" onClick={()=>setOpen(true)}>추가</button></div>{msg&&<p className="mb-3 text-sm text-slate-300">{msg}</p>}
    <div className="overflow-hidden rounded-xl border border-slate-800"><table className="w-full text-sm"><thead className="bg-slate-900 text-slate-400"><tr><th className="p-3 text-left">등록일</th><th className="p-3 text-left">이름</th><th className="p-3 text-left">전화번호</th><th className="p-3 text-left">연락방법</th><th className="p-3 text-left">상대보험사</th><th className="p-3 text-left">현황</th><th className="p-3 text-left">담당자</th><th className="p-3 text-left">최근 메모</th><th className="p-3 text-right">액션</th></tr></thead><tbody className="divide-y divide-slate-800">{rows.map(row=><><tr key={row.id} className="table-row-clickable" onClick={()=>router.push(`/admin/leads/${row.id}`)}><td className="p-3 text-slate-400">{formatKSTDateTime(row.created_at)}</td><td className="p-3 font-bold text-white">{row.name}</td><td className="p-3">{row.phone}</td><td className="p-3">{row.contact_method||"-"}</td><td className="p-3">{row.insurance_company||"-"}</td><td className="p-3"><StatusBadge status={row.status}/></td><td className="p-3">{row.manager_name||row.profiles?.name||"-"}</td><td className="max-w-xs truncate p-3 text-slate-400">{row.latest_note||"-"}</td><td className="p-3 text-right"><button onClick={(e)=>{e.stopPropagation(); setMemoId(memoId===row.id?null:row.id)}} className="btn btn-secondary mr-2">메모</button>{role==="ADMIN"&&<button onClick={(e)=>{e.stopPropagation(); del(row.id)}} className="btn btn-danger">삭제</button>}</td></tr>{memoId===row.id&&<tr><td colSpan={9} className="bg-slate-950 p-4"><form action={saveMemo} className="space-y-2"><input type="hidden" name="lead_id" value={row.id}/><textarea className="input min-h-24" name="content" defaultValue={row.latest_note||""}/><button className="btn btn-primary" disabled={pending}>메모 저장</button></form></td></tr>}</> )}</tbody></table></div>
    <Modal open={open} onClose={()=>setOpen(false)} title="교통사고 DB 추가"><form action={submit} className="grid gap-3"><input className="input" name="name" placeholder="이름"/><input className="input" name="phone" placeholder="전화번호"/><select className="input" name="contact_method">{CONTACT_METHODS.map(v=><option key={v}>{v}</option>)}</select><input className="input" name="insurance_company" placeholder="상대보험사"/><select className="input" name="status">{LEAD_STATUSES.map(v=><option key={v} value={v}>{LEAD_STATUS_LABEL[v]}</option>)}</select><select className="input" name="assigned_to"><option value="">담당자 계정 선택</option>{profiles.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><select className="input" name="manager_name"><option value="">담당자명 선택</option>{staffNames.map(n=><option key={n}>{n}</option>)}</select><textarea className="input min-h-24" name="memo" placeholder="메모"/><div className="flex justify-end gap-2"><button type="button" className="btn btn-secondary" onClick={()=>setOpen(false)}>취소</button><button className="btn btn-primary" disabled={pending}>확인</button></div></form></Modal>
  </>;
}
